### ISSUE TITLE
absFloat 함수 테스트케이스 관련

### ISSUE THREAD

**Issue by chaeypar** [SNU-ARC/2023_fall_comarch_PA2#1]
안녕하세요, 
Infinity 관련 궁금한 사항이 있어 문의드립니다.

처음 absFloat() 함수 구현 시 주어진 스펙에 따라 Infinity 혹은 NaN에 해당하는 input이 들어올 경우 그대로 input을 반환하도록 하였는데요. 제 구현에 따르면, Negative Infinity에 해당하는 0xff800000이 input으로 들어올 경우 그대로 0xff800000을 반환하게 되는데 아래와 같은 에러 메시지가 발생합니다. 
 혹시나 해서 Negative Infinity의 경우에는 input을 바로 반환하지 않도록 구현하니 테스트를 통과하였습니다. 일반적으로 컴퓨터 구조에서 Infinity라고 하면 Negative Infinity를 제외한 Positive Infinity만을 의미하는 것인지 궁금합니다.
![image](https://github.com/SNU-ARC/2023_fall_comarch_PA2/assets/115587321/be8df3fe-14ad-4ab1-885e-4358d2c31e61)

감사합니다.

**Comment by bgsim** [comment]
안녕하세요, 조교 심봉근입니다.

수업자료 3번 pdf의 30쪽 페이지를 확인해주시면, infinity와 nan에 대한 설명이 있습니다.

해당 설명과 문제를 잘 읽어주시기 바랍니다.

감사합니다.
