### ISSUE TITLE
./btest 관련 질문드립니다.

### ISSUE THREAD

**Issue by tree330** [SNU-ARC/2023_fall_comarch_PA2#10]
안녕하십니까.
make btest를 실행하던 과정에 오류가 발생하였는데 해결하지 못하여 질문을 드립니다.
bits/libc-header-start-h: No Such file or directory라는 오류가 발생하는데, 파일을 다 지우고 다시 git clone을 하거나 git pull을 하더라도 계속 같은 오류가 발생하고 있습니다.

sudo apt-get install gcc gcc-multilib
git clone https://github.com/SNU-ARC/2023_fall_comarch_PA2
명령어를 모두 올바르게 실행한 것 같은데, 어떤 부분에서 문제가 발생하는 것인지 잘 모르겠어서 도움을 요청드립니다.
해결을 위해서 도움이 될지는 모르겠지만, ./dlc 명령어는 매우 원활하게 수행되는 상태입니다. 

감사합니다.

**Comment by bgsim** [comment]
안녕하세요.

관련해서 몇 가지 검색해보았는데요, 해결방법도 여러가지가 있는 것 같았습니다.

대부분 32bit / 64bit architecture 차이에 따라 나올 수 있다는 말이 많은 것 같구요
가장 간단한 해결방법으로는

sudo apt-get install gcc-multilib g++-multilib

를 통해서 해결이 가능하다고 합니다.

위방식으로 해결된다면 close 부탁드리겠습니다.

**Comment by tree330** [comment]
제가 일단 네트워크 쪽에 문제가 있는 것 같아서 고친 후에 말씀해주신 방법을 시도해보고 다시 질문드리겠습니다!
