### ISSUE TITLE
unsigned data type 관련하여 질문드립니다

### ISSUE THREAD

**Issue by hanE111** [SNU-ARC/2023_fall_comarch_PA2#11]
bits.c line 100에서는 "You are expressly forbidden to: " ... " 5. Use any data type other than int or unsigned." (line 105) 라는데
./dlc bits.c 를 하면 "Illegal data type: unsigned"이라 뜹니다.

어느게 맞나요?

**Comment by bgsim** [comment]
안녕하세요

line 100에 있는 것은 floating point의 rule입니다.

integer rule은 55줄부터입니다. (62줄에 int만 활용 가능하다고 명시되어있음)

혹시 어떤 문제에서 unsigned를 사용하셨나요?

코멘트 남겨주시기 바랍니다.

감사합니다.

**Comment by hanE111** [comment]
답변 감사합니다!
unsigned int는 5번 bitfilter에서 사용했습니다
