### ISSUE TITLE
Q8 absFloat

### ISSUE THREAD

**Issue by jhy213** [SNU-ARC/2023_fall_comarch_PA2#12]
source code 주석에는 Nan이면 input값을 그대로 출력하라고 되어있고
PA2파일에는 Nan이거나 Infinity이면 input값을 그대로 출력하라고 되어있는데

./btest 명령어로 테스트한 결과
Infinity를 체크하지 않아도 통과하는 것으로 보입니다.

source code주석과 PA2 설명 중 어느 것을 따라야 하는지,
그리고 테스트결과에 대해서 질문드립니다.

**Comment by bgsim** [comment]
안녕하세요.

죄송합니다. 제가 표현을 잘못해두었습니다.

Infinity 는 Absolute 값을 찾을 수 있습니다.
주석에 써있는 대로 NaN인 경우에만 input을 그대로 출력해주시기 바랍니다.

내용 업데이트해두도록 하겠습니다.

감사합니다.

**Comment by jhy213** [comment]
넵 감사합니다!
