### ISSUE TITLE
./btest 관련 질문

### ISSUE THREAD

**Issue by kimon2002** [SNU-ARC/2023_fall_comarch_PA2#13]
안녕하세요, 조교님. 다름이 아니라 btest 파일 실행시 사진과 같은 오류(exec format error)가 발생하는 현상 때문에 글을 작성합니다.
![캡처](https://github.com/SNU-ARC/2023_fall_comarch_PA2/assets/80949753/e659a0af-8dd4-4447-9922-7ec3bcb98819)

구글링을 하여도 마땅히 좋은 해결책을 찾지 못하여 질문을 남깁니다. 감사합니다.

**Comment by bgsim** [comment]
안녕하세요. 조교입니다.

저도 처음 보는 문제이지만, 열심히 구글링을 하다보니 gcc 에서 문제가 있을 수 있는 것 같습니다.

sudo apt-get --purge remove gcc gcc-multilib
sudo apt-get update
sudo apt-get install gcc gcc-multilib
make clean & make

과정을 다시 진행한 후에 과정별로 문제가 없는지 확인부탁드립니다.

감사합니다.

**Comment by kimon2002** [comment]
안녕하세요, 말씀해주신 방법을 따라봤지만 똑같은 결과가 발생했습니다. 다만, 새로운 가상머신에서 이를 실행하니 문제 없이 돌아가는 것을 확인했습니다! 감사합니다. :>
