### ISSUE TITLE
./dlc parse error

### ISSUE THREAD

**Issue by kic2242** [SNU-ARC/2023_fall_comarch_PA2#14]
make를 할 때도 아무런 이상 없습니다.

그런데, 유독 ./dlc bits.c를 하면 parse error가 뜨고, 그 후에 선언한 variable들에 대해서는 undeclared variable이라고 칭얼댑니다.

상황을 보면, 아래와 같은 변수의 재정의하는 상황이후부터 그런 현상이 발생합니다.

전혀 문제 없어보이는데 왜 이렇게 parse error를 띄우면서 그러는지 궁금합니다.

1 // int a = 1234;
2 // a = a + 1234;
3 // 
4 // int b = 1;
5 // b = b + 1;
>>> bits.c:4: parse error 
>>> bits.c:5: undeclared variable 'b'

**Comment by bgsim** [comment]
안녕하세요.

원래는 make를 할 때도 문제가 있었어야 했을 것 같은데 잘 되나봅니다.

c언어 특성상 선언부가 모두 위에 있어야 하고, 실행부가 항상 그보다 아래에 있어야 합니다.
c++로 바뀌면서 여러 제한들이 바뀌었지만 c언어 때에는 모든 변수의 선언을 항상 함수 초반부에서 모두 이뤄져야 했었습니다.
for(int a; ... ) 역시 위와 같은 이유로 활용할 수 없었던 적이 있습니다.

https://github.com/SNU-ARC/2023_fall_comarch_PA2/issues/9
를 참고해주시면 더 좋을 것 같습니다.

감사합니다.
