### ISSUE TITLE
Large Constants 관련 질문

### ISSUE THREAD

**Issue by seatosky2002** [SNU-ARC/2023_fall_comarch_PA2#15]
안녕하세요!

bits.c 26줄 integer coding rules에 we are not allowed to use big constants such as 0xffffffff이라 적혀있는데 8, 9, 10번에도 해당되나요?

**Comment by bgsim** [comment]
안녕하세요

아니요 float 문제에는 제한없이 사용하셔도 문제 없습니다.

감사합니다
