### ISSUE TITLE
addAndDivideBy4 관

### ISSUE THREAD

**Issue by fyoon46** [SNU-ARC/2023_fall_comarch_PA2#3]
안녕하세요,

addAndDivideBy4 문제에서 overflow가 발생하면 x를 return해야 하는데, 아래 사진처럼 0x80000000, 0x80000000을 input으로 넣으면 0x80000000이 아닌 0이 나와야 한다고 뜹니다. 그런데, test.c에 있는 정답 함수를 복사해서 실행하면 제가 생각하는 것처럼 x(0x80000000)가 print 됩니다. 무엇이 문제인가요?

<img width="732" alt="image" src="https://github.com/SNU-ARC/2023_fall_comarch_PA2/assets/52787727/6df6aba3-bf7c-4d24-986d-7e579316da41">

**Comment by bgsim** [comment]
안녕하세요 조교 심봉근입니다.

어떤 원인인지 잘 모르겠으나 환경에 따라 위처럼 출력되는경우가 있는것같습니다.

말씀하신대로 정상적으로 실행하면 정상적인 값이 출력되는것을 확인했으니 
git reset
make clean
make
를 통해서 초기화 후 재시도 부탁드리겠습니다

**Comment by jeonghonoh** [comment]
저도 동일한 현상을 겪고 있는데 말씀하신 방식대로 
git reset
make clean
make
을 진행해도 동일한 현상이 반복되고 있습니다.

**Comment by choco-bear** [comment]
저도 동일한 현상을 겪고 있으며, 말씀하신대로
```
git reset
make clean
make
```
을 진행해도 같은 현상이 반복되고 있습니다.
wsl에서 작동시킬 때에는 정상적인 값이 출력되는 것으로 보이는데, 채점 과정에서는 문제가 없을 것이라고 판단해도 무방한지 궁금합니다.

**Comment by bgsim** [comment]
혹시 테스트를 어떤식으로하셨나요?

./btest 를 했을 때 해당항목에서 같은 결과가 나올까요?

아니면 ./btest -f addAndDivideBy4 -1 0x8000000 -2 0x8000000 으로 따로 동작하신걸까요?

그리고 혹시 환경도 공유해주실수있나요?

**Comment by fyoon46** [comment]
테스트는 ./btest를 했고, 실행환경은 window에서 virtual box를 다운로드하여 구축했습니다.
몇 가지 실험을 해보니 아래와 같이 -O option을 넣었을 때와 넣지 않았을 때 차이가 난다는 것을 알아냈습니다.

![image](https://github.com/SNU-ARC/2023_fall_comarch_PA2/assets/52787727/b8c3891b-587d-4335-af81-0931b78b2c01)

**Comment by bgsim** [comment]
안녕하세요. 조교 심봉근입니다.

일단 특정 환경에서의 원인은 찾은것같습니다.
int sum32 = 0 인 상태에서 (long long)sum32 로 캐스팅하면 (long long)sum32 가 0이 아닌 0xffffffff00000000 이 되는 컴파일러 버그가 있는 것 같습니다.

현재로서는 특정 환경에서의 버그를 찾는 것은 어려울 것 같아 tests.c를 우회하고자 합니다.

long long sum = (long long)x + (long long)y;
if(sum & 0xffffffff00000000)
    return x;
else
    return (x+y)/4;

로 우회하고자 합니다.

여러 환경에서 테스트해보고 문제없는 경우에 git에 반영해두고 공지드리도록 하겠습니다.

관련하여 동일한 문제가 발생하시는 분들 께서는 일단 위의 test code로 임의수정하여 동작해주시길 부탁드리겠습니다.

감사합니다.

**Comment by jeonghonoh** [comment]
![image](https://github.com/SNU-ARC/2023_fall_comarch_PA2/assets/101174133/5a401d9a-dfdc-43e7-b580-7eff7add334d)
overflow가 발생하는 상황이 아닌 것 같은데 비슷한 문제로 다음과 같은 버그도 있는 것 같습니다.

**Comment by bgsim** [comment]
원인을 찾은 것 같습니다.

64bit architecture에서 레지스터는 64bit 으로 가지고있게 됩니다.

그런데 컴파일러 환경에 따라 내부적으로 연산은 64bit으로 하고, 보여줄 때 32bit만 잘라서 보여주는 버그가 있는 것 같습니다.
해당 버그라고 생각하는 이유는 아래와 같이 test했을 때의 결과가 예상과 다르게 나오기 때문입니다.

// x = 0x80000000, y = 0x80000000
int sum32 = (x+y)&0xffffffff;
printf("%d, %lld\n",sum32, (long long)sum32);
// 예상 결과 : 0, 0
// 실제 결과 : 0, -4294967296 // 0xffffffff00000000

일반적인 경우 위와 같은 상황은 있어선 안되며, 컴파일러 최적화중 발생하는 버그로 생각됩니다.
또한 몇 번의 수정을 거치다보면 예상결과처럼 정상적으로 출력되는 것도 확인됩니다.

따라서 함수를 아래와 같이 수정하였을 때 문제없이 동작할 것으로 생각하고 있습니다.

int sum32 = (int)(((long long)x + (long long)y) & 0x00000000ffffffff);
long long sum = (long long)x + (long long)y;
if ((long long)sum32 == sum)
    return (x+y)/4;
else
    return x;

위와 같은 경우 strict하게 64bit 연산 후 int로 bit만 잘라서 보여주는 것과 실제 연산의 결과가 같은지를 비교할 것이기 때문에 잘 동작할 것이라 생각됩니다.

몇 번의 테스트 후 정상적이라 판단될 때 공지드리도록 하겠습니다.

감사합니다.
