### ISSUE TITLE
Time out issue for #Q10 (compareFloat)

### ISSUE THREAD

**Issue by Byeol-Haneul** [SNU-ARC/2023_fall_comarch_PA2#4]
안녕하세요, compareFloat 함수에 대한 ./btest 수행 시 timeout 문제에 대해 질문드립니다.
`btest.c` header에서 time limit을 조절하면 test가 통과하는 것을 보았고, #Q10만 수행 시 `time ./btest`가 12s 정도의 실행시간이 걸리는 것을 확인했습니다. 가상환경에서 수행해서 느린 것이 아닐까 조심스럽게 짐작해보는데 혹시 채점 시 time limit 10s가 strict limit인지 알고 싶습니다.

**Comment by bgsim** [comment]
안녕하세요. 조교 심봉근입니다

제 환경에서 10s timeout을 걸었던 이유는 문제들이 잘못해서 무한루프에 걸리지 않았음을 확인하기 위함입니다.

그러나 너무 비효율적인 코드작성으로 제 환경에서도 timeout이 발생한다면 불이익이 있을 수 있습니다

감사합니다
