### ISSUE TITLE
addAndDivideBy4 관련하여 질문드립니다.

### ISSUE THREAD

**Issue by LyEEhD** [SNU-ARC/2023_fall_comarch_PA2#7]
안녕하세요.

이번 PA2 를 해결하면서 addAndDivideBy4 를 테스트하는 과정에서 0x80000000 0x80000000 의 결과값을 0 이랑 비교하게 되는 문제를 겪고 있습니다. ETL 에 있는 다른 학생분이 올린 질문을 참고하여 git reset 과 make clean 을 시도한 후 에도 같은 결과가 나왔습니다.  tests.c 에 존재하는 함수 구현을 보하도 문제가 없어 보였습니다. 이는 어떻게 해결하면 좋을까요?

감사합니다.

**Comment by bgsim** [comment]
[addAndDivideBy4 Issue Link](https://github.com/SNU-ARC/2023_fall_comarch_PA2/issues/3) 
를 참고해주시기 바랍니다

확인 후 곧 공지를 드릴 예정이니 그때까지 현재 issue open해두도록하겠습니다
감사합니다

**Comment by bgsim** [comment]
코드 수정 후 공지 올려드렸습니다.

감사합니다.
